<div class="box_content box_round popular_cities">
	<h2><?php echo _("Destinations Populaires");?></h2>		
		<p style="line-height:1.8em;">
		<a style="font-size:<?php echo rand(8,16);?>pt;" title="<?php echo $this->Db_country->get_city("England","London",$this->site_lang);?>" href="<?php echo site_url($this->Db_country->get_city_link("England","London",$this->site_lang));?>"><?php echo $this->Db_country->get_city("England","London",$this->site_lang);?></a>, 
		<a style="font-size:<?php echo rand(8,16);?>pt;" title="<?php echo $this->Db_country->get_city("Italy","Rome",$this->site_lang);?>" href="<?php echo site_url($this->Db_country->get_city_link("Italy","Rome",$this->site_lang));?>"><?php echo $this->Db_country->get_city("Italy","Rome",$this->site_lang);?></a>, 
		<a style="font-size:<?php echo rand(8,16);?>pt;" title="<?php echo $this->Db_country->get_city("Spain","Barcelona",$this->site_lang);?>" href="<?php echo site_url($this->Db_country->get_city_link("Spain","Barcelona",$this->site_lang));?>"><?php echo $this->Db_country->get_city("Spain","Barcelona",$this->site_lang);?></a>, 
		<a style="font-size:<?php echo rand(8,16);?>pt;" title="<?php echo $this->Db_country->get_city("France","Paris",$this->site_lang);?>" href="<?php echo site_url($this->Db_country->get_city_link("France","Paris",$this->site_lang));?>"><?php echo $this->Db_country->get_city("France","Paris",$this->site_lang);?></a>, 
		<a style="font-size:<?php echo rand(8,16);?>pt;" title="<?php echo $this->Db_country->get_city("Netherlands","Amsterdam",$this->site_lang);?>" href="<?php echo site_url($this->Db_country->get_city_link("Netherlands","Amsterdam",$this->site_lang));?>"><?php echo $this->Db_country->get_city("Netherlands","Amsterdam",$this->site_lang);?></a>, 
		<a style="font-size:<?php echo rand(8,16);?>pt;" title="<?php echo $this->Db_country->get_city("Ireland","Dublin",$this->site_lang);?>" href="<?php echo site_url($this->Db_country->get_city_link("Ireland","Dublin",$this->site_lang));?>"><?php echo $this->Db_country->get_city("Ireland","Dublin",$this->site_lang);?></a>, 
		<a style="font-size:<?php echo rand(8,16);?>pt;" title="<?php echo $this->Db_country->get_city("Spain","Madrid",$this->site_lang);?>" href="<?php echo site_url($this->Db_country->get_city_link("Spain","Madrid",$this->site_lang));?>"><?php echo $this->Db_country->get_city("Spain","Madrid",$this->site_lang);?></a>, 
		<a style="font-size:<?php echo rand(8,16);?>pt;" title="<?php echo $this->Db_country->get_city("Czech Republic","Prague",$this->site_lang);?>" href="<?php echo site_url($this->Db_country->get_city_link("Czech Republic","Prague",$this->site_lang));?>"><?php echo $this->Db_country->get_city("Czech Republic","Prague",$this->site_lang);?></a>, 
		<a style="font-size:<?php echo rand(8,16);?>pt;" title="<?php echo $this->Db_country->get_city("Germany","Berlin",$this->site_lang);?>" href="<?php echo site_url($this->Db_country->get_city_link("Germany","Berlin",$this->site_lang));?>"><?php echo $this->Db_country->get_city("Germany","Berlin",$this->site_lang);?></a>, 
		<a style="font-size:<?php echo rand(8,16);?>pt;" title="<?php echo $this->Db_country->get_city("Italy","Venice",$this->site_lang);?>" href="<?php echo site_url($this->Db_country->get_city_link("Italy","Venice",$this->site_lang));?>"><?php echo $this->Db_country->get_city("Italy","Venice",$this->site_lang);?></a>, 
		<a style="font-size:<?php echo rand(8,16);?>pt;" title="<?php echo $this->Db_country->get_city("Italy","Florence",$this->site_lang);?>" href="<?php echo site_url($this->Db_country->get_city_link("Italy","Florence",$this->site_lang));?>"><?php echo $this->Db_country->get_city("Italy","Florence",$this->site_lang);?></a>, 
		<a style="font-size:<?php echo rand(8,16);?>pt;" title="<?php echo $this->Db_country->get_city("Austria","Vienna",$this->site_lang);?>" href="<?php echo site_url($this->Db_country->get_city_link("Austria","Vienna",$this->site_lang));?>"><?php echo $this->Db_country->get_city("Austria","Vienna",$this->site_lang);?></a>, 
		<a style="font-size:<?php echo rand(8,16);?>pt;" title="<?php echo $this->Db_country->get_city("Hungary","Budapest",$this->site_lang);?>" href="<?php echo site_url($this->Db_country->get_city_link("Hungary","Budapest",$this->site_lang));?>"><?php echo $this->Db_country->get_city("Hungary","Budapest",$this->site_lang);?></a>,
		<a style="font-size:<?php echo rand(8,16);?>pt;" title="<?php echo $this->Db_country->get_city("USA","New York",$this->site_lang);?>" href="<?php echo site_url($this->Db_country->get_city_link("USA","New York",$this->site_lang));?>"><?php echo $this->Db_country->get_city("USA","New York",$this->site_lang);?></a>,  
		<a style="font-size:<?php echo rand(8,16);?>pt;" title="<?php echo $this->Db_country->get_city("ecosse","edimbourg",$this->site_lang);?>" href="<?php echo site_url($this->Db_country->get_city_link("ecosse","edimbourg",$this->site_lang));?>"><?php echo $this->Db_country->get_city("ecosse","edimbourg",$this->site_lang);?></a>, 
		<a style="font-size:<?php echo rand(8,16);?>pt;" title="<?php echo $this->Db_country->get_city("Sweden","Stockholm",$this->site_lang);?>" href="<?php echo site_url($this->Db_country->get_city_link("Sweden","Stockholm",$this->site_lang));?>"><?php echo $this->Db_country->get_city("Sweden","Stockholm",$this->site_lang);?></a>, 
		<a style="font-size:<?php echo rand(8,16);?>pt;" title="<?php echo $this->Db_country->get_city("Germany","Munich",$this->site_lang);?>" href="<?php echo site_url($this->Db_country->get_city_link("Germany","Munich",$this->site_lang));?>"><?php echo $this->Db_country->get_city("Germany","Munich",$this->site_lang);?></a>, 
		<a style="font-size:<?php echo rand(8,16);?>pt;" title="<?php echo $this->Db_country->get_city("France","Nice",$this->site_lang);?>" href="<?php echo site_url($this->Db_country->get_city_link("France","Nice",$this->site_lang));?>"><?php echo $this->Db_country->get_city("France","Nice",$this->site_lang);?></a>, 
		<a style="font-size:<?php echo rand(8,16);?>pt;" title="<?php echo $this->Db_country->get_city("Greece","Athens",$this->site_lang);?>" href="<?php echo site_url($this->Db_country->get_city_link("Greece","Athens",$this->site_lang));?>"><?php echo $this->Db_country->get_city("Greece","Athens",$this->site_lang);?></a>, 
		<a style="font-size:<?php echo rand(8,16);?>pt;" title="<?php echo $this->Db_country->get_city("italy","milan",$this->site_lang);?>" href="<?php echo site_url($this->Db_country->get_city_link("italy","milan",$this->site_lang));?>"><?php echo $this->Db_country->get_city("italy","milan",$this->site_lang);?></a>, 
		<a style="font-size:<?php echo rand(8,18);?>pt;" title="<?php echo $this->Db_country->get_city("portugal","lisbon",$this->site_lang);?>" href="<?php echo site_url($this->Db_country->get_city_link("portugal","lisbon",$this->site_lang));?>"><?php echo $this->Db_country->get_city("portugal","lisbon",$this->site_lang);?></a>,
		<a style="font-size:<?php echo rand(8,18);?>pt;" title="<?php echo $this->Db_country->get_city("Belgium","Brussels",$this->site_lang);?>" href="<?php echo site_url($this->Db_country->get_city_link("Belgium","Brussels",$this->site_lang));?>"><?php echo $this->Db_country->get_city("Belgium","Brussels",$this->site_lang);?></a>
	</p>	
</div>