<?php
echo _('Hello')." $first_name $last_name<br />";
echo "<br />";
echo _('Good news!')."<br />";
echo "<br />";
echo _('We have found a great offer for your group.')."<br />";
echo "<br />";
echo _('Please take a look at the attached file for more details.')."<br />";
echo "<br />";
echo _('Please do not hesitate to contact me if you have any questions.')."<br />";
echo "<br />";
echo _('Sincerely.')."<br />";
echo "<br />";

echo _('Customer Service.')."<br />";
echo $this->config->item('site_name');
echo "<br />";
echo "<br />";
echo "<br />";
echo "1."._("Travel details")."<br />";
echo _("Country").": ".$search_country."<br />";
echo _("City").": ".$search_city."<br />";
echo _("Date").": ".$datepick."<br />";
echo _("Nuits:")." ".$search_night."<br />";
echo "<br />";
echo "2."._("Group details")."<br />";
echo _("Male:")." ".$nb_male_gp."<br />";
echo _("Female:")." ".$nb_female_gp."<br />";
echo _("Youngest age").": ".$lower_age."<br />";
echo "<br />";
echo "3."._("Staff/teachers/Coaches/Bus drivers Details")."<br />";
echo _("Persons").": ".$nb_person_staff."<br />";
echo _("Room type requested").": "._($rm_type)." (".$rm_type.")<br />";
echo "<br />";
echo "4."._("Requirements")."<br />";
echo _("Breakfast").": "._($breakfast)."<br />";
echo _("Dinner").": "._($dinner)."<br />";
echo _("Most Important").": "._($most_important)."<br />";
echo "<br />";
echo "5."._("Your details")."<br />";
echo _("Prénom").": ".$first_name."<br />";
echo _("Nom").": ".$last_name."<br />";
echo _("Addresse Email").": ".$email."<br />";
echo _("Phone number").": ".$phone_number."<br />";
echo "<br />";
echo "6."._("Additional information/requests")."<br />";
echo _($demand)."<br />";
echo $more_info."<br />";
?>
